name: leetcode
description: Solved LeetCode problems
version: 0.0.1-dev
homepage: https://github.com/Vikrech/leetcode
environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  meta: 1.7.0

dev_dependencies:
  test: 1.16.0
  coverage: any